# .github/workflows/miner.yml
name: GigaFile Miner (Manual Only)

on:
  workflow_dispatch:

jobs:
  miner:
    name: Run GigaFile Miner script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run inline Python miner
        run: |
          python3 - << 'EOF'
          import requests, random

          lower = "abcdefghijklmnopqrstuvwxyz"
          upper = lower.upper()
          num   = "0123456789"

          def rand_str(l):
              return ''.join(random.choices(lower + upper + num, k=l))

          url = "https://xgf.nu/"

          try:
              while True:
                  s = rand_str(random.randint(4,5))
                  new_url = url + s
                  print(f"\r[+] [ {s} ] mining...", end=" ")
                  r = requests.get(new_url, timeout=10)
                  if len(r.url) > 30:
                      print(f"\r[*] [ {s} ] discovered --> {r.url}")
          except KeyboardInterrupt:
              print("\nbye")
          EOF
