name: GigaFile Miner (Manual Only)

on:
  workflow_dispatch:

jobs:
  miner:
    runs-on: ubuntu-latest

    steps:
      - name: Run GigaFile Miner script
        run: |
          python3 - << 'EOF'
          import requests, random, time, sys

          lower = "abcdefghijklmnopqrstuvwxyz"
          upper = lower.upper()
          num   = "0123456789"

          def rand_str(l):
              return ''.join(random.choices(lower + upper + num, k=l))

          url = "https://xgf.nu/"

          max_iterations = 100  # 最大試行回数（無限ループ防止）
          hit_count = 0

          try:
              for _ in range(max_iterations):
                  s = rand_str(random.randint(4,5))
                  new_url = url + s
                  sys.stdout.write(f"[+] Trying: {new_url}\n")
                  sys.stdout.flush()
                  try:
                      r = requests.get(new_url, timeout=10)
                      if len(r.url) > 30 and r.url != new_url:
                          hit_count += 1
                          print(f"[!] HIT [{hit_count}]: {r.url}")
                  except requests.exceptions.ReadTimeout:
                      print(f"[!] Timeout on {new_url}")
                  except requests.exceptions.RequestException as e:
                      print(f"[!] Request failed on {new_url}: {e}")
                  time.sleep(0.5)
          except KeyboardInterrupt:
              print("\nStopped manually.")

          print(f"\nFinished mining. Total hits: {hit_count}")
          EOF
