name: GigaFile Miner (Manual Only)

on:
  workflow_dispatch:

jobs:
  miner:
    runs-on: ubuntu-latest

    steps:
      - name: Run GigaFile Miner script
        run: |
          python3 - << 'EOF'
          import requests, random, time

          lower = "abcdefghijklmnopqrstuvwxyz"
          upper = lower.upper()
          num   = "0123456789"

          def rand_str(l):
              return ''.join(random.choices(lower + upper + num, k=l))

          url = "https://xgf.nu/"

          try:
              while True:
                  s = rand_str(random.randint(4,5))
                  new_url = url + s
                  print(f"[+] [ {s} ] mining...", end="\r")
                  try:
                      r = requests.get(new_url, timeout=10)
                      if len(r.url) > 30:
                          print(f"[*] [ {s} ] discovered --> {r.url}")
                  except requests.exceptions.ReadTimeout:
                      print(f"[!] [ {s} ] Timeout, retrying...")
                  except requests.exceptions.RequestException as e:
                      print(f"[!] [ {s} ] Request failed: {e}")
                  time.sleep(0.5)  # 連続アクセスしすぎ防止
          except KeyboardInterrupt:
              print("\nbye")
          EOF
